CREATE TABLE IF NOT EXISTS corpus_record (
    id BIGINT NOT NULL COMMENT '主键',
    capture_id VARCHAR(64) NOT NULL COMMENT '一次截图采集 ID',
    comment_index INT NOT NULL COMMENT '同一截图内第几条评论',
    raw_content TEXT NULL COMMENT '截图中可见的原始评论',
    context_target TEXT NULL COMMENT '截图中可见的上下文原文',
    platform VARCHAR(64) NULL COMMENT '来源平台',
    original_publish_time DATETIME NULL COMMENT '原评论发布时间',
    collected_time DATETIME NOT NULL COMMENT '系统采集时间',
    oss_bucket VARCHAR(128) NOT NULL COMMENT 'OSS Bucket 名称',
    oss_object_key VARCHAR(512) NOT NULL COMMENT 'OSS Object Key',
    image_hash VARCHAR(64) NOT NULL COMMENT '图片 SHA-256',
    tags JSON NULL COMMENT '模型生成标签数组，数据库中不带 #',
    model_raw_response JSON NULL COMMENT 'Gemini 原始返回',
    parse_status VARCHAR(32) NOT NULL COMMENT '解析状态',
    error_message TEXT NULL COMMENT '错误信息',
    markdown_path VARCHAR(512) NULL COMMENT 'Markdown 文件路径',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id),
    KEY idx_image_hash (image_hash),
    KEY idx_capture_id (capture_id),
    UNIQUE KEY uk_capture_comment (capture_id, comment_index)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='截图语料记录';
