CREATE TABLE IF NOT EXISTS capture_record (
    id BIGINT NOT NULL COMMENT '主键',
    capture_id VARCHAR(64) NOT NULL COMMENT '一次截图采集 ID',
    image_hash VARCHAR(64) NOT NULL COMMENT '图片 SHA-256',
    oss_bucket VARCHAR(128) NOT NULL COMMENT 'OSS Bucket 名称',
    oss_object_key VARCHAR(512) NOT NULL COMMENT 'OSS Object Key',
    mime_type VARCHAR(128) NULL COMMENT '上传图片 MIME 类型',
    provider VARCHAR(64) NULL COMMENT '多模态 Provider',
    model VARCHAR(128) NULL COMMENT '多模态模型名称',
    process_status VARCHAR(32) NOT NULL COMMENT '采集任务处理状态',
    retry_count INT NOT NULL DEFAULT 0 COMMENT '后台处理重试次数',
    last_error_type VARCHAR(64) NULL COMMENT '最后一次错误类型',
    last_failed_at DATETIME NULL COMMENT '最后一次失败时间',
    error_message TEXT NULL COMMENT '错误信息',
    model_raw_response JSON NULL COMMENT '多模态 Provider 原始返回',
    duplicate TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否重复截图任务',
    `force` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否强制重新识别',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_capture_id (capture_id),
    KEY idx_capture_image_hash (image_hash),
    KEY idx_capture_process_status (process_status),
    KEY idx_capture_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='截图采集任务记录';

CREATE TABLE IF NOT EXISTS corpus_record (
    id BIGINT NOT NULL COMMENT '主键',
    capture_id VARCHAR(64) NOT NULL COMMENT '一次截图采集 ID',
    comment_index INT NOT NULL COMMENT '同一截图内第几条评论',
    raw_content TEXT NULL COMMENT '截图中可见的原始评论',
    context_target TEXT NULL COMMENT '截图中可见的上下文原文',
    platform VARCHAR(64) NULL COMMENT '来源平台',
    original_publish_time DATETIME NULL COMMENT '原评论发布时间',
    collected_time DATETIME NOT NULL COMMENT '系统采集时间',
    oss_bucket VARCHAR(128) NOT NULL COMMENT 'OSS Bucket 名称',
    oss_object_key VARCHAR(512) NOT NULL COMMENT 'OSS Object Key',
    image_hash VARCHAR(64) NOT NULL COMMENT '图片 SHA-256',
    tags JSON NULL COMMENT '模型生成标签数组，数据库中不带 #',
    model_raw_response JSON NULL COMMENT '多模态 Provider 原始返回',
    parse_status VARCHAR(32) NOT NULL COMMENT '解析状态',
    error_message TEXT NULL COMMENT '错误信息',
    retry_count INT NOT NULL DEFAULT 0 COMMENT '后台处理重试次数',
    last_error_type VARCHAR(64) NULL COMMENT '最后一次错误类型',
    last_failed_at DATETIME NULL COMMENT '最后一次失败时间',
    review_status VARCHAR(32) NOT NULL DEFAULT 'UNREVIEWED' COMMENT '人工校对状态',
    reviewed_raw_content TEXT NULL COMMENT '人工修正后的评论原文',
    reviewed_context_target TEXT NULL COMMENT '人工修正后的上下文原文',
    reviewed_tags JSON NULL COMMENT '人工修正后的标签数组',
    reviewed_at DATETIME NULL COMMENT '人工校对时间',
    review_note TEXT NULL COMMENT '人工校对备注',
    markdown_path VARCHAR(512) NULL COMMENT 'Markdown 文件路径',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id),
    KEY idx_image_hash (image_hash),
    KEY idx_capture_id (capture_id),
    KEY idx_review_status (review_status),
    KEY idx_collected_time_id (collected_time DESC, id DESC),
    UNIQUE KEY uk_capture_comment (capture_id, comment_index)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='截图语料记录';

CREATE TABLE IF NOT EXISTS recognition_run (
    id BIGINT NOT NULL COMMENT '主键',
    capture_record_id BIGINT NULL COMMENT '截图采集任务 ID',
    capture_id VARCHAR(64) NOT NULL COMMENT '一次截图采集 ID',
    image_hash VARCHAR(64) NOT NULL COMMENT '图片 SHA-256',
    provider VARCHAR(64) NOT NULL COMMENT '多模态 Provider',
    model VARCHAR(128) NULL COMMENT '多模态模型名称',
    status VARCHAR(32) NOT NULL COMMENT '识别运行状态',
    item_count INT NOT NULL DEFAULT 0 COMMENT '识别出的评论数量',
    started_at DATETIME NOT NULL COMMENT '识别开始时间',
    finished_at DATETIME NULL COMMENT '识别结束时间',
    duration_ms BIGINT NULL COMMENT '识别耗时毫秒',
    input_tokens BIGINT NULL COMMENT '输入 token 数',
    output_tokens BIGINT NULL COMMENT '输出 token 数',
    total_tokens BIGINT NULL COMMENT '总 token 数',
    estimated_cost DECIMAL(12,6) NULL COMMENT '成本估算',
    error_type VARCHAR(64) NULL COMMENT '错误类型',
    error_message TEXT NULL COMMENT '错误信息',
    model_raw_response JSON NULL COMMENT '多模态 Provider 原始返回',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id),
    KEY idx_recognition_capture_record (capture_record_id),
    KEY idx_recognition_capture_id (capture_id),
    KEY idx_recognition_provider_model (provider, model),
    KEY idx_recognition_status (status),
    KEY idx_recognition_started_at (started_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='模型识别运行记录';

CREATE TABLE IF NOT EXISTS feishu_ingestion_task (
    id BIGINT NOT NULL COMMENT '主键',
    event_id VARCHAR(128) NOT NULL COMMENT '飞书事件 ID',
    message_id VARCHAR(128) NOT NULL COMMENT '飞书消息 ID',
    chat_id VARCHAR(128) NULL COMMENT '飞书会话 ID',
    sender_id VARCHAR(128) NULL COMMENT '飞书发送者 ID',
    image_key VARCHAR(256) NOT NULL COMMENT '飞书图片资源 key',
    capture_record_id BIGINT NULL COMMENT 'Symptom-Graph 截图任务 ID',
    capture_id VARCHAR(64) NULL COMMENT 'Symptom-Graph 采集批次 ID',
    image_hash VARCHAR(64) NULL COMMENT '图片 SHA-256',
    status VARCHAR(32) NOT NULL COMMENT '飞书接入任务状态',
    error_message TEXT NULL COMMENT '错误信息',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_feishu_event_id (event_id),
    UNIQUE KEY uk_feishu_message_image (message_id, image_key),
    KEY idx_feishu_capture_record (capture_record_id),
    KEY idx_feishu_status (status),
    KEY idx_feishu_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='飞书图片接入任务记录';
